### ISSUE TITLE
validate input for `duffle build`

### ISSUE THREAD

**Issue by bacongobbler** [deislabs/duffle#527]
As we have changed the fields on duffle.toml mulitple times during the PoC, we have a lot of TOML files that are invalid input to `duffle build`, but `duffle build` will still silently accept that input without validation, ending up in weird scenarios like this one:

duffle.toml:

```toml
name = "wordpress"
registry = "cnab"
components = ["cnab"]
version = "0.2.0"
```

```console
$ duffle build .
==> Successfully built bundle wordpress:
```

Instead, `duffle build` should fail when it doesn't find fields that are required from duffle.toml.
