### ISSUE TITLE
cannot resolve tilde in file credential

### ISSUE THREAD

**Issue by sbawaska** [deislabs/duffle#720]
I created a credential file with a tilda:
```
→ cat ~/.duffle/credentials/myk8s.yaml
name: myk8s
credentials:
- name: kubeconfig
  source:
    path: ~/.kube/config
```
This file exists on my dev machine, however, duffle install command is not able to resolve it:
```
→ duffle install myriff riff --credentials myk8s
Error: credential "kubeconfig": open ~/.kube/config: no such file or directory
```
Providing a fully qualified path works.
